# -*- coding: utf-8 -*-
"""imdb_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HVg3I5l11zZ_Kea-vr3Ihapbg-Rq5iN6
"""

import pandas as pd
import numpy as np

movies = pd.read_csv('/imdb-top-1000.csv')
movies

from google.colab import drive
drive.mount('/content/drive')

movies.head()

# best avg meta score actor genre combo
movies.groupby(['Star1' , 'Genre'])['Metascore'].mean()

genres = movies.groupby('Genre')
genres

# top 3 genre by Total Earning
movies.groupby('Genre')['Gross'].sum().sort_values(ascending = False).head(3)

movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

#director with most popularity
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

genres.sum()



# movies starting with a
def foo(groups):
  return groups['Series_Title'].str.startswith('A').sum()

genres.apply(foo)

# normalized imdb rating group wise
def normal(group):
  group['norm_rating']= group['IMDB_Rating'] - group['IMDB_Rating'].mean()/(group['IMDB_Rating'].max() - group['IMDB_Rating'].min())
  return group
genres.apply(normal)